### ISSUE TITLE
为提高安全性，默认对所有输出escape

### ISSUE THREAD

**Issue by leizongmin** [leizongmin/tinyliquid#10]
+ 默认对所有输出执行 escape 转义，如果不需要转义，则使用 unescape 来反转
+ 在编译模板的时候提供一个选项来取消默认自动转义

**Comment by mercmobily** [comment]
Is this something important? How does it affect us?

Google translate:

-----------------------
The default implementation of the output of all `escape` escaping, if not escape, uses the `unescape` to reverse

When compiling a template provide an option to cancel the default automatic escaping
------------------------

**Comment by leizongmin** [comment]
Just a plan, I don't finsh this feature yet. So you don't need to worry about it.
Maybe in the future we can pass an `autoEscape=true` option to enable this feature while rendering a template.
