### ISSUE TITLE
"if" tags treat all variables as lowercase

### ISSUE THREAD

**Issue by tsion** [leizongmin/tinyliquid#30]
Here's an example program:
``` javascript
var tl = require('tinyliquid');

function runTemplate(template, locals) {
  var render = tl.compile(template);
  var context = tl.newContext({locals: locals});
  render(context, function(err) {
    if (err) { return console.log(err); }
    console.log(context.getBuffer());
  });
}

// Pay attention to foobar vs fooBar
runTemplate('{% if fooBar %}.{% endif %} {{ fooBar }}', {fooBar: true});
runTemplate('{% if foobar %}.{% endif %} {{ foobar }}', {foobar: true});
runTemplate('{% if fooBar %}.{% endif %} {{ fooBar }}', {foobar: true});
```

The output is:
```
 true
. true
. 
```

But it should be:
```
. true
. true
 
```

As you can see, the `if` check for `fooBar` fails when it shouldn't in the first test case and succeeds when it shouldn't in the third. The output tag gets its value correctly. The third test case shows the problem: `if fooBar` checks for `foobar`.

I checked the generated AST for the above templates and found out it generates a `[ 1, 2, 'EXISTS', [ 1, 2, 'LOCALS', 'foobar', 'foobar', null ] ]` node for the condition `if fooBar`. It turns out to be an issue with the parser, which indiscriminately calls `toLowerCase` on everything in the condition (I'm guessing to parse keywords like `and` and `or` case-insensitively). See here: https://github.com/leizongmin/tinyliquid/blob/master/lib/parser.js#L552

**Comment by leizongmin** [comment]
I have just fixed this problem, you can install the lastest version `tinyliquid@0.2.28`.
Thanks.

**Comment by tsion** [comment]
Thanks a lot for the quick fix!
