### ISSUE TITLE
How actually to use Pagination?

### ISSUE THREAD

**Issue by ksugiarto** [leizongmin/tinyliquid#31]
I'm sorry that I'm not quite understand how to use it, I think I tried several way and research when using:

    {{count | pagination: size, currentPage}}

it always simply return `object Object`

Can you please provide more explanation about it? Many thanks

**Comment by leizongmin** [comment]
This filter will returns an object like this:

```
{
  current: page,
  next: page + 1,
  previous: page - 1,
  list: list
}
```

+ `current`: current page number
+ `next`: the next page number
+ `previous`: the previous page number
+ `list`: list of all page number, such as `[1, 2, 3, '...', 8, 9, 10]`

You can see the code here: https://github.com/leizongmin/tinyliquid/blob/master/lib/filters.js#L724

**Comment by ksugiarto** [comment]
Sorry, I still can't understand it. I tried with a simpler example like:

    {{ 20 | pagination: 5, 1 }}

My assumption:
I have `20 items`,
I want to divide it into `5 items per page`,
and now I'm in the `page 1`.

But I still get `[object Object]` as the result. Which variable position that I put it wrong? Thanks

**Comment by leizongmin** [comment]
I mean `{{ 20 | pagination: 5, 1 }}` returns an object, you cannot print it.
Just use it to gererate pagination HTML like this (with Bootstrap):

```html
{% assign pagination_info = count|pagination:size,currentPage %}
<div class="text-center">
  <ul class="pagination-turning">
    <li><a href="{{pagination_info.previous.url|escape}}">&laquo;</a></li>
    {% for item in pagination_info.list %}
      {% if item == pagination_info.current %}
    <li class="active">
      <a href="#">{{item|escape}}</a>
    </li>
      {% else %}
        {% if item == '...' %}
    <li class="disabled">
      <a href="#">{{item|escape}}</a>
    </li>
        {% else %}
    <li>
      <a href="/list?p={{item|escape}}">{{item|escape}}</a>
    </li>
        {% endif %}
      {% endif %}
    {% endfor %}
    <li><a href="/list?p={{pagination_info.next|escape}}">&raquo;</a></li>
  </ul>
</div>
```

**Comment by ksugiarto** [comment]
Hi @leizongmin sorry I can't manage to research upon it in such time, but thanks for your time giving another deeper explanations :D
