### ISSUE TITLE
Can I use for in range?

### ISSUE THREAD

**Issue by ksugiarto** [leizongmin/tinyliquid#32]
I tried and read that in your wiki there is no such filter for using `for` within certain variable range, like:

    {% assign num = 5 %}
    {% for i in (1..num) %}
      {{ i }} 
    {% endfor %}

If there is anyways, can you please provide some explanation about it? Many Thanks

**Comment by leizongmin** [comment]
TinyLiquid was not supported this usage before. But now, in the new version, you can use like that.
Please install the latest version: `tinyliquid@0.2.29`
Thank you.

**Comment by ksugiarto** [comment]
Ok, thanks so much for the fast respond. :D

**Comment by ksugiarto** [comment]
Perhaps some notes for people that already use `tinyliquid` using `express-liquid`. We need to install the latest `tinyliquid` on the `express-liquid` still instead of install it alone. Do I metion it right @leizongmin ?

**Comment by leizongmin** [comment]
The latest version of `express-liquid` dependencies on `tinyliquid@0.2.x`, I think you just need to __reinstall__ `express-liquid`
