### ISSUE TITLE
Possible timing issue in for loops

### ISSUE THREAD

**Issue by markbirbeck** [leizongmin/tinyliquid#34]
I have to apologise that I've not been able to create a test case for you, but I've not been able to recreate the problem directly in your test suite. I feel bad about that, because I love the library and I'm using it a lot!

Anyway, I'll try to provide as much information as I can about the problem, so here goes....

(Sorry that is so long-winded but it's in lieu of some tests to help identify the problem. :)

I have a bunch of blog posts -- 82 to be precise -- and I'm using a `for` loop to render their entries like this:

```html
{% for post in site.posts %}
<div>
  <h3><a href="{{ post.url | prepend: site.baseurl }}">{{ post.title }}</a></h3>
</div>
{% endfor %}
```

I hadn't noticed until recently that although I'm getting 82 titles, I'm actually missing one, but the numbers are correct because one is duplicated! So instead of this:

  1 2 3 4 ... 82

I get this:

  82 2 3 4 ... 82

I discovered that if I add some output lines before the `for` loop I could get it to work, which made me wonder if it was a timing issue.

I figured it was worth a try to change your call in `utils.js` from `setImmediate()` to `process.nextTick()` and sure enough, I then got all 82 entries correctly.

I notice at line 500 of `utils.js` that you are trying to create a `setImmediate()` function that maps to `process.nextTick()`, and I guess it's so that your code will also work in the browser. I imagine that the problem is simply that newer versions of nodejs are providing this function, so its presence is not a sufficient test for whether you are in a browser environment or not.

Anyway, that change definitely fixes the problem for me, although as I said, I failed to replicate the problem in your test suite. Here's the kind of thing I was trying, but this test passes:

```javascript
  var site = {
    posts: []
  };
  var result = '';
  for (var i = 0; i < 10000; i++) {
    var title = 'Post ' + i;
    site.posts.push({ title: title });
    result.concat(title);
  }
  context.setLocals('posts', site);
  it('large #for', function (done) {
    common.taskList()
      .add(function (done) {
        common.render(context, '{% for post in site.posts %}{{ post.title }}{% endfor %}', function (err, buf) {
          assert.equal(err, null);
          assert.equal(buf, result);
          context.clearBuffer();
          done();
        });
      })
      .end(done);
  });
```

However, the fact remains that unless I change your `setImmediate()` call to `process.nextTick()`, my template continually gives the pattern that I described, where one element is duplicated, taking the place of another element.

**Comment by markbirbeck** [comment]
Ok...scratch this...or at least some of it. The problem can still appear if using `process.nextTick()`.

**Comment by leizongmin** [comment]
I've doing some change: in the newest version, it required `setImmediate()` function, if the JavaScript runtime does not supported this it will throws an error.
