### ISSUE TITLE
Include paths

### ISSUE THREAD

**Issue by cameronjroe** [leizongmin/tinyliquid#35]
Getting an error when trying to include a path. It's pointing to the file itself.

The file exists in `src/_includes/learn/navbar-affix.liquid`
It's getting rendered from `src/_includes/learn/hero.liquid`
```
{% include learn/navbar-affix %}
```

error:
```
Error: ENOENT: no such file or directory, open 'src/_includes/navbar-affix.liquid'
```

**Comment by leizongmin** [comment]
`tinyliquid` only provide you to use `context` instance to register your include file handler:

```javascript
context.onInclude(function (name, callback) {
  // in your case, name="learn/navbar-affix"
  callback(null, tinyliquid.parse(your_template_file_content));
});
```

see wiki: https://github.com/leizongmin/tinyliquid/wiki/The-Context-Instance#set-the-include-file-handler-contextonincludefn

If you don't set up this include handler, when you use the `include` tag, it will throws an error.
 **So I guess it's not `tinyliquid` itself's problem**

**Comment by cameronjroe** [comment]
How is the file getting resolved? Would it be ideal to resolve a path to the argument provided?

**Comment by leizongmin** [comment]
```javascript
var tinyliquid = require('tinyliquid');

// include root path
var root = '/path/to';

// resolve include filename
function resolveFile(name) {
  // this is a simple example
  return path.resolve(root, name);
}

// base content
vat baseContext = tinyliquid.newContext();
baseContext.onInclude(function (name, callback) {
  var file = resolveFile(root, name);
  fs.readFile(file, function (err, content) {
    if (err) return callback(err);
    var ast = tinyliquid.parse(content);
    callback(null, ast);
  });
});

// then use this baseContext to render tinyliquid template
```

If you are using tinyliquid in Express.js, you can try this package `express-liquid`: https://github.com/leizongmin/express-liquid

(You can also reviews the souce of this project to see how it works)

**Comment by cameronjroe** [comment]
So if I don't put includes in folders then all partials will live on a top-level of the includes folder. This makes for a really messy project when it scales. Any chance tinyliquid can support just adjusting this resolve to include a path inside of includes?

**Comment by cameronjroe** [comment]
Also, I'm really not even sure where I'd go about using a context? I'm using tinyliquid merely for consolidate.js to be used with metalsmith-layouts.

**Comment by cameronjroe** [comment]
It turns out it's an issue with consolidate.js.
