### ISSUE TITLE
Object not showing

### ISSUE THREAD

**Issue by cameronroe** [leizongmin/tinyliquid#39]
I'm iterating over some posts, but in the for loop and the post include I'm not able to output json of the post object. It's clearly getting set when I use the attributes such as `post.title`, `post.path`, but when I pipe the entire object through `{{post | json}}` it's showing an empty object -> `{}`. This isn't the first time this has happened. Any idea of what's happening here?

```
<ul class="post-list">
  {% for post in collections.posts %}
   {{post | json}} -> {}
    <li>
      {% include post post=post %}
    </li>
  {% endfor %}
</ul>
```

**Comment by leizongmin** [comment]
I ever met the same problem, it seems the problem will happening in some special cases.
Can you provide some sample data of `collections.posts`?

**Comment by cameronjroe** [comment]
I think it's the json filter. Is it working?

**Comment by leizongmin** [comment]
the json filter:

```javascript
exports.json = function (input) {
  try {
    var ret = JSON.stringify(input);
  } catch (err) {
    return '{}';
  }
  return typeof ret !== 'string' ? '{}' : ret;
};
```

it seems that was something wrong when stringify the `post`. I suggest you try to do `JSON.stringify()` in your programs to check it:

```
collections.posts.forEach(function (item) {
  try {
    JSON.stringify(item);
  } catch (err) {
    console.log('fail', item, err);
  }
});
```
