### ISSUE TITLE
modulo filter?

### ISSUE THREAD

**Issue by cameronroe** [leizongmin/tinyliquid#42]
Is the modulo filter included?

**Comment by leizongmin** [comment]
default filter list see here: https://github.com/leizongmin/tinyliquid/wiki/Default-Filters

**Comment by leizongmin** [comment]
If you want to register a custom filter, see here: https://github.com/leizongmin/tinyliquid/wiki/The-Context-Instance#set-the-sync-filter-contextsetfiltername-fn
