### ISSUE TITLE
object not being scoped properly

### ISSUE THREAD

**Issue by cameronroe** [leizongmin/tinyliquid#45]
I'm using a for loop to loop through a collection:

```
{% for product in home_featured.products %}
        {% include 'product-grid-collage' with product %}
{% endfor %}
```

The `product` object also exists globally, and it's not being scoped to the "product-grid-collage" include.

```
<pre>
{{ product | json }} // comes out as the global in product-grid-collage
</pre>
```

**Comment by cameronroe** [comment]
Is there any way to automatically include the variables in the scope of the for loop within the include?

**Comment by cameronroe** [comment]
For example `product` would be the items in the `home_featured.products`

**Comment by cameronroe** [comment]
?

**Comment by cameronroe** [comment]
?

**Comment by cameronroe** [comment]
? Dude.

**Comment by leizongmin** [comment]
Maybe this is a bug. But you can fix this problem like this:

```
{% for product in home_featured.products %}
        {% assign product2 = product %}
        {% include 'product-grid-collage' with product2 %}
{% endfor %}
```
