### ISSUE TITLE
json filter not working

### ISSUE THREAD

**Issue by cameronroe** [leizongmin/tinyliquid#46]
object clearly full of data:

`{{ pagination | json }} --> {}`

**Comment by cameronroe** [comment]
?

**Comment by cameronroe** [comment]
Can we just update the Wiki together to provide exact docs on how the json filter is working?

**Comment by leizongmin** [comment]
I'm so sorry, because I am working on other project these days.
Can you help me fix this problem? you can edit the Wiki, or any pull request is welcome.

**Comment by cameronroe** [comment]
Would you know why the json filter is not working?

**Comment by leizongmin** [comment]
We can find the `json()` source code from here: https://github.com/leizongmin/tinyliquid/blob/master/lib/filters.js#L639

```javascript
/**
 * Return a JSON string of the object
 *
 * @param {Object} input
 * @return {String}
 */
exports.json = function (input) {
  try {
    var ret = JSON.stringify(input);
  } catch (err) {
    return '{}';
  }
  return typeof ret !== 'string' ? '{}' : ret;
};
```

If we don't pass the `pagination` data to render the template, then it would be `null`.

If we pretty sure we have passed data to it, maybe that was a problem when `JSON.stringify()`, as I know, this following thing maybe occur an error:

`pagination` has circular property, for example:

```javascript
var a = {};
a.a = a;
JSON.stringify(a)
```

this code will throws `Uncaught TypeError: Converting circular structure to JSON`, in the `json()` function, we catch this error, and return `{}`. If so, it's not tinyliquid itself's problem.
